### ISSUE TITLE
Sample JavaScript project

### ISSUE THREAD

**Issue by rodrigovilar** [fabricioepa/lab-hexagon-java#1]
As a developer, I want to use a sample project to create a JavaScript client for this hexagonal service.

If this issue does not fit the project scope, it can be resolved in another branch.

**Comment by fabricioepa** [comment]
It is totally possible. If you want to do it quickly you just need to create the static resources inside the folder /lab-hexagon-java/integration/rest-adapter/src/main/resources/static/, and then access the url http://host:8080/resourcename

**Comment by fabricioepa** [comment]
Issue timeout =)
